meta:
  title: "Blocklet Services | Reusable, Built-in Functionality"
  description: "Learn about the standardized, out-of-the-box services that blocklets can use, such as Decentralized Identity (DID) Connect, multi-channel notifications, and theme management, enabling developers to build features faster."
  image: "mediakit://service-blocklets-overview.png"
sections:
  - sectionName: "ServicesHero"
    sectionSummary: "An energetic introduction to Blocklet Services, highlighting the core benefit of accelerating development by using pre-built, production-ready functionalities. This section uses a split-hero format to pair a compelling value proposition with a visual of the service management dashboard."
    splitHeroTitle: "Build Faster, Not From Scratch"
    splitHeroDescription: "Stop reinventing the wheel! Plug into a universe of production-ready services and ship your features at lightning speed. From secure logins to powerful analytics, we handle the essentials so you can focus on what makes your app unique."
    splitHeroRightImage: "mediakit://service-blocklets-overview.png"
    splitHeroActions:
      - text: "Explore the SDK"
        link: "link:///sdk"
      - text: "See Architecture"
        link: "link:///architecture"
  - sectionName: "CoreServicesGrid"
    sectionSummary: "A scannable grid showcasing the key categories of Blocklet Services. Each card uses an icon and a brief, benefit-oriented description to quickly communicate the breadth of capabilities available to developers, making the abstract concept of 'services' tangible and exciting."
    threeColumnGridTitle: "Everything You Need, Right Out of the Box"
    list:
      - sectionName: "DIDConnectCard"
        sectionSummary: "Highlights the Decentralized Identity (DID) Connect service, focusing on secure, passwordless authentication and user management capabilities."
        iconName: "mdi:account-lock-outline"
        cardTitle: "Decentralized Identity"
        cardDescription: "Give your users the magic of passwordless login! Manage users, issue digital passports, and build a trusted community with our built-in DID Connect services."
      - sectionName: "NotificationsCard"
        sectionSummary: "Showcases the multi-channel notification service, emphasizing its simplicity and reach for engaging users across different platforms."
        iconName: "mdi:bell-ring-outline"
        cardTitle: "Multi-Channel Notifications"
        cardDescription: "Keep your users in the loop, wherever they are. Send beautiful emails, push notifications, and webhook alerts through a single, simple API."
      - sectionName: "ThemingCard"
        sectionSummary: "Features the theme management service, explaining how developers can easily customize the look and feel of their applications."
        iconName: "mdi:palette-swatch-outline"
        cardTitle: "Dynamic Theming"
        cardDescription: "Make your app feel like home. Effortlessly manage branding, customize color schemes, and configure typography to create a stunning user experience."
      - sectionName: "SecurityCard"
        sectionSummary: "Focuses on the built-in security services, reassuring developers that their applications are protected by default."
        iconName: "mdi:shield-check-outline"
        cardTitle: "Enhanced Security"
        cardDescription: "Sleep better at night knowing your app is protected. Our services include a built-in WAF, rate limiting, and CORS handling to keep threats at bay."
      - sectionName: "AnalyticsCard"
        sectionSummary: "Highlights the operations and analytics services, showing developers they have immediate access to important usage data."
        iconName: "mdi:chart-bar"
        cardTitle: "Operations & Analytics"
        cardDescription: "Get instant insights! Monitor traffic, view detailed logs, and understand user behavior with our comprehensive, built-in analytics dashboards."
      - sectionName: "IntegrationsCard"
        sectionSummary: "Promotes the developer-focused integration services, such as WebHooks and API keys, for extending application functionality."
        iconName: "mdi:api"
        cardTitle: "Developer Integrations"
        cardDescription: "Connect to anything. Manage API keys, configure webhooks, and integrate with external systems to extend your app's power and reach."
  - sectionName: "DIDConnectFeature"
    sectionSummary: "A deep-dive into the DID Connect service, using a split-hero layout to visually showcase the user management interface while explaining its powerful features like custom passports and federated login. This section reinforces a key value proposition of the platform."
    splitHeroLeftImage: "mediakit://service-did-connect-members.png"
    splitHeroTitle: "The Future of Identity is Here"
    splitHeroDescription: "Onboard and manage your users with the power of Decentralized Identity. DID Connect provides a complete toolkit for passwordless authentication, flexible user roles, verifiable credentials (passports), and even federated login across your entire app ecosystem. It's secure, seamless, and ready to go."
    splitHeroActions:
      - text: "Learn More in Docs"
        link: "link:///architecture"
      - text: ""
        link: ""
  - sectionName: "WebsiteManagementFeature"
    sectionSummary: "This section highlights the Website Management services, using a visual of the branding configuration to demonstrate how easily developers can control their app's appearance. It emphasizes the no-code aspect of managing domains, branding, and themes."
    splitHeroTitle: "Your App, Your Brand"
    splitHeroDescription: "Take full control of your application's presentation. Our website services make it a breeze to manage custom domains, upload your logo, define color palettes, and set typography. You'll have a beautifully branded, professional-looking site up and running in minutes, no CSS wizardry required!"
    splitHeroRightImage: "mediakit://service-website-branding.png"
    splitHeroActions:
      - text: "Read the Docs"
        link: "link:///architecture"
      - text: ""
        link: ""
  - sectionName: "SecurityFeatureSpotlight"
    sectionSummary: "A dedicated section to emphasize the robust, built-in security features. It uses a strong headline and a visual of the gateway configuration to build trust and assure developers that the platform prioritizes security, handling complex threats so they don't have to."
    featureSectionTitle: "Build with Confidence on a Secure Foundation"
    featureSectionDescription: "Security isn't an afterthought; it's built into the core of Blocklet Services. From a ModSecurity-based Web Application Firewall (WAF) to intelligent request blocking and rate limiting, we provide a hardened environment that protects your application and your users from common threats right from the start."
    featureSectionBottomImage: "mediakit://settings-gateway-configuration.png"
  - sectionName: "ServicesFAQ"
    sectionSummary: "An FAQ section that addresses common technical questions developers might have about using Blocklet Services. This proactively provides answers to key implementation details, reducing friction and encouraging adoption."
    faqTitle: "Frequently Asked Questions"
    faqList:
      - question: "How do I use these services in my blocklet?"
        answer: "It's incredibly easy! The Blocklet SDK automatically provides access to all available services. You just import what you need and start calling methods—no complex setup or configuration required."
      - question: "Are the services customizable?"
        answer: "Absolutely! Many services can be configured through your blocklet's preferences interface or by setting environment variables, giving you the flexibility to tailor their behavior to your app's specific needs."
      - question: "What is the performance impact of using these services?"
        answer: "Minimal. The services are highly optimized and run as part of the core Blocklet Server environment. They are designed to be lightweight and efficient, ensuring your application remains fast and responsive."
      - question: "Can I create my own services that other blocklets can use?"
        answer: "Yes! That's the power of the component architecture. Any blocklet can define and expose its own services, allowing you to create reusable, shared functionality across your applications."
      - question: "How are services updated?"
        answer: "Services are part of the Blocklet Server runtime. When you update your Blocklet Server, you get the latest features, security patches, and performance improvements for all services automatically."
  - sectionName: "ServicesCTA"
    sectionSummary: "A final, action-oriented call-to-action that encourages developers to take the next step. It directs them to the SDK documentation, providing a clear path from learning about services to actually using them in their code."
    ctaTitle: "Ready to Supercharge Your App?"
    ctaDescription: "Dive into our SDK and see how easy it is to integrate these powerful, pre-built services into your next project. Spend less time on boilerplate and more time creating amazing user experiences!"
    cta:
      - text: "Start Building with the SDK"
        link: "link:///sdk"
      - text: "Back to Platform Home"
        link: "link:///home"
