# Project information for page publishing
projectName: Blocklet Platform
projectDesc: The Blocklet Platform is a comprehensive ecosystem that simplifies
  the development, deployment, and management of modern, decentralized web
  applications with built-in identity and security.
projectLogo: ""
projectId: pg4d0000-0000-4000-a000-000000000000
projectSlug: /ezfj

# =============================================================================
# Website Configuration
# =============================================================================

# Purpose: What's the main outcome you want readers to achieve?
# Available options (uncomment and modify as needed):
#   landingPage      - Landing page / Homepage: Convert visitors into users or customers
#   ecommerce        - E-commerce / Online store: Sell products or services online
#   portfolio        - Portfolio / Showcase: Display creative work, projects, or achievements
#   corporate        - Corporate / Business: Professional business website with company information
#   blog             - Blog / Content site: Share articles, news, and regular content updates
#   saas             - SaaS / Software product: Promote and onboard users to software services
#   nonprofit        - Non-profit / Community: Promote causes, accept donations, engage volunteers
#   education        - Educational / Learning: Provide courses, tutorials, or educational content
#   mixedPurpose     - Multi-purpose website: Comprehensive website covering multiple needs
pagePurpose:
  - landingPage

# Target Audience: Who will be reading this most often?
# Available options (uncomment and modify as needed):
#   customers        - Customers / End users: People who buy or use your products/services
#   businessOwners   - Business owners / Entrepreneurs: People running businesses looking for solutions
#   marketers        - Marketing teams: People promoting products or managing campaigns
#   designers        - Designers / Creative professionals: People focused on visual design and user experience
#   developers       - Developers / Technical users: People building or integrating technical solutions
#   investors        - Investors / Stakeholders: People evaluating business potential and growth
#   jobSeekers       - Job seekers / Potential employees: People looking for career opportunities
#   students         - Students / Learners: People seeking educational content or resources
#   generalPublic    - General public / Mixed audience: Broad audience with varied interests and backgrounds
targetAudienceTypes:
  - developers
  - customers

# Website Scale: How many pages should your website have?
# Available options (uncomment and modify as needed):
#   singlePage         - Single Page (only 1 page): All content consolidated into 1 page
#   minimal            - Minimal (2-6 pages): Core pages only - quick to launch
#   standard           - Standard (7-12 pages): Complete website with main sections [RECOMMENDED]
#   comprehensive      - Comprehensive (12+ pages): Full-featured website with detailed sections
#   aiDecide           - Let AI decide: Analyze project complexity and suggest appropriate scale
websiteScale: standard

# Custom Rules: Define specific page generation rules and requirements
rules: >-
  1. Generate a home page for the entire Blocklet platform, as well as a subpage for each component of the platform.

  2. The home page should include a section for each component — such as Blocklet Server, Blocklet Service, Blocklet SDK, Blocklet CLI, Blocklet Store, and Blocklet Launcher — and each section should link to its corresponding subpage.

  3. Each component subpage should focus on the component itself, serve as a dedicated landing page, and include a link back to the home page.

  4. The home page should use a Full Background Hero_center layout at the top, while all other subpages should use a Grid Right layout instead.

  5. each page must include a footer section with clickable links to all other pages, ensuring users can easily navigate across the entire site.

  6. On the blocklet-cli page, if there are any .cast files available, use them instead of PNG images to display code.

# Glossary: Define project-specific terms and definitions
# glossary: "@glossary.md"  # Path to markdown file containing glossary definitions

locale: en
translateLanguages:
  - zh
pagesDir: .aigne/web-smith/pages # Directory to save generated pages
sourcesPath: # Source code paths to analyze
  - ./src
lastGitHead: 750353c94df7920cb61452923b64f8272aaa9d32
# Checkout ID for website deployment service
checkoutId: ""
# appUrl: https://www.blocklet.io
appUrl: https://staging.websmith.aigne.io
projectCover: .aigne/web-smith/cover.png
