meta:
  title: "Blocklet 服务 | 可复用、内置的功能"
  description: "了解 Blocklet 可使用的标准化、开箱即用的服务，例如去中心化身份（DID）连接、多渠道通知和主题管理，助力开发者更快地构建功能。"
  image: "mediakit://service-blocklets-overview.png"
sections:
  - sectionName: "ServicesHero"
    sectionSummary: "对 Blocklet 服务的有力介绍，强调通过使用预构建的、生产就绪的功能来加速开发的核心优势。本节采用分栏英雄板块格式，将引人注目的价值主张与服务管理仪表盘的视觉效果相结合。"
    splitHeroTitle: "更快构建，而非从零开始"
    splitHeroDescription: "停止重复造轮子！接入一个充满生产就绪服务的宇宙，以闪电般的速度发布您的功能。从安全登录到强大的分析功能，我们处理好基础事务，让您可以专注于打造应用的独特之处。"
    splitHeroRightImage: "mediakit://service-blocklets-overview.png"
    splitHeroActions:
      - text: "探索 SDK"
        link: "link:///sdk"
      - text: "查看架构"
        link: "link:///architecture"
  - sectionName: "CoreServicesGrid"
    sectionSummary: "一个易于浏览的网格，展示了 Blocklet 服务的关键类别。每张卡片都使用一个图标和一段简短的、以效益为导向的描述，以快速传达可供开发者使用的广泛功能，使“服务”这一抽象概念变得具体而激动人心。"
    threeColumnGridTitle: "一切所需，开箱即用"
    list:
      - sectionName: "DIDConnectCard"
        sectionSummary: "重点介绍去中心化身份（DID）连接服务，专注于安全、无密码的身份验证和用户管理功能。"
        iconName: "mdi:account-lock-outline"
        cardTitle: "去中心化身份"
        cardDescription: "为您的用户带来无密码登录的神奇体验！通过我们内置的 DID Connect 服务，管理用户、颁发数字护照并建立一个值得信赖的社区。"
      - sectionName: "NotificationsCard"
        sectionSummary: "展示多渠道通知服务，强调其在不同平台上吸引用户的简便性和覆盖范围。"
        iconName: "mdi:bell-ring-outline"
        cardTitle: "多渠道通知"
        cardDescription: "让您的用户随时随地了解最新动态。通过一个简单统一的 API 发送精美的电子邮件、推送通知和 Webhook 警报。"
      - sectionName: "ThemingCard"
        sectionSummary: "介绍主题管理服务，解释开发者如何轻松自定义其应用程序的外观和感觉。"
        iconName: "mdi:palette-swatch-outline"
        cardTitle: "动态主题"
        cardDescription: "让您的应用充满亲切感。轻松管理品牌、自定义配色方案并配置排版，创造出色的用户体验。"
      - sectionName: "SecurityCard"
        sectionSummary: "专注于内置的安全服务，让开发者放心，他们的应用程序默认受到保护。"
        iconName: "mdi:shield-check-outline"
        cardTitle: "增强安全性"
        cardDescription: "让您的应用得到保护，从此高枕无忧。我们的服务包括内置的 WAF、速率限制和 CORS 处理，可有效抵御威胁。"
      - sectionName: "AnalyticsCard"
        sectionSummary: "重点介绍运营和分析服务，向开发者展示他们可以立即访问重要的使用数据。"
        iconName: "mdi:chart-bar"
        cardTitle: "运营与分析"
        cardDescription: "即时获取洞察！通过我们全面、内置的分析仪表盘监控流量、查看详细日志并了解用户行为。"
      - sectionName: "IntegrationsCard"
        sectionSummary: "推广面向开发者的集成服务，如 WebHooks 和 API 密钥，用于扩展应用程序功能。"
        iconName: "mdi:api"
        cardTitle: "开发者集成"
        cardDescription: "连接万物。管理 API 密钥、配置 Webhook 并与外部系统集成，以扩展您应用的功能和覆盖范围。"
  - sectionName: "DIDConnectFeature"
    sectionSummary: "深入探讨 DID Connect 服务，采用分栏英雄板块布局，直观展示用户管理界面的同时，解释其强大的功能，如自定义护照和联合登录。本节强化了平台的一个关键价值主张。"
    splitHeroLeftImage: "mediakit://service-did-connect-members.png"
    splitHeroTitle: "身份的未来，已然来临"
    splitHeroDescription: "利用去中心化身份的力量来引导和管理您的用户。DID Connect 提供了一个完整的工具包，用于无密码身份验证、灵活的用户角色、可验证凭证（护照），甚至支持在整个应用生态系统中进行联合登录。它安全、无缝且开箱即用。"
    splitHeroActions:
      - text: "在文档中了解更多"
        link: "link:///architecture"
      - text: ""
        link: ""
  - sectionName: "WebsiteManagementFeature"
    sectionSummary: "本节重点介绍网站管理服务，通过品牌配置的视觉效果，展示开发者可以多么轻松地控制其应用的外观。它强调了管理域名、品牌和主题的无代码方面。"
    splitHeroTitle: "您的应用，您的品牌"
    splitHeroDescription: "完全掌控您应用程序的外观呈现。我们的网站服务让管理自定义域名、上传您的徽标、定义调色板和设置排版变得轻而易举。您将在几分钟内拥有一个品牌精美、外观专业的网站，无需任何高深的 CSS 技巧！"
    splitHeroRightImage: "mediakit://service-website-branding.png"
    splitHeroActions:
      - text: "阅读文档"
        link: "link:///architecture"
      - text: ""
        link: ""
  - sectionName: "SecurityFeatureSpotlight"
    sectionSummary: "一个专门强调强大内置安全功能的章节。它使用强有力的标题和网关配置的视觉效果来建立信任，并向开发者保证平台优先考虑安全性，处理复杂的威胁，让他们无需操心。"
    featureSectionTitle: "在安全的基础上放心构建"
    featureSectionDescription: "安全不是事后补充，而是内建于 Blocklet 服务的核心。从基于 ModSecurity 的 Web 应用程序防火墙（WAF）到智能请求拦截和速率限制，我们提供了一个加固的环境，从一开始就保护您的应用程序和用户免受常见威胁。"
    featureSectionBottomImage: "mediakit://settings-gateway-configuration.png"
  - sectionName: "ServicesFAQ"
    sectionSummary: "一个常见问题解答部分，解决了开发者在使用 Blocklet 服务时可能遇到的常见技术问题。这主动为关键实施细节提供了答案，减少了障碍并鼓励采用。"
    faqTitle: "常见问题"
    faqList:
      - question: "如何在我的 Blocklet 中使用这些服务？"
        answer: "非常简单！Blocklet SDK 会自动提供对所有可用服务的访问权限。您只需导入所需内容并开始调用方法——无需复杂的设置或配置。"
      - question: "这些服务可以自定义吗？"
        answer: "当然可以！许多服务都可以通过您的 Blocklet 偏好设置界面或设置环境变量进行配置，让您能够灵活地根据应用的特定需求调整其行为。"
      - question: "使用这些服务对性能有何影响？"
        answer: "影响极小。这些服务经过高度优化，并作为核心 Blocklet Server 环境的一部分运行。它们被设计为轻量级和高效率，确保您的应用程序保持快速和响应灵敏。"
      - question: "我可以创建自己的服务供其他 Blocklet 使用吗？"
        answer: "可以！这就是组件化架构的强大之处。任何 Blocklet 都可以定义和暴露自己的服务，从而允许您在应用程序之间创建可复用的共享功能。"
      - question: "服务是如何更新的？"
        answer: "服务是 Blocklet Server 运行时的一部分。当您更新 Blocklet Server 时，您将自动获得所有服务的最新功能、安全补丁和性能改进。"
  - sectionName: "ServicesCTA"
    sectionSummary: "最后一个以行动为导向的号召，鼓励开发者迈出下一步。它将他们引向 SDK 文档，为从了解服务到在代码中实际使用服务提供了一条清晰的路径。"
    ctaTitle: "准备好为您的应用增压了吗？"
    ctaDescription: "深入了解我们的 SDK，看看将这些功能强大、预先构建的服务集成到您的下一个项目中是多么容易。花更少的时间在样板代码上，将更多时间用于创造卓越的用户体验！"
    cta:
      - text: "开始使用 SDK 构建"
        link: "link:///sdk"
      - text: "返回平台主页"
        link: "link:///home"